name: test

on:
  push:
    branches:
    - 'main'
    - 'helm-*'

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Publish helm chart
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: testdata
